### ISSUE TITLE
Does work when running the gulp task 'run'

### ISSUE THREAD

**Issue by aaronksaunders** [chrisdias/ionic-todo-vscode#1]
Live reload requires you to input the ip address, but the output window is not accepting at

**Comment by chrisdias** [comment]
Hi Aaron - 

Yes, I've seen this too.  Our output window in VS Code isn't interactive so there is no way to enter in the IP address. You'll need to run the task from the terminal instead of from within VS Code.  Sorry about this, known issue in the tool.

**Comment by aaronksaunders** [comment]
You might want to edit the blog post or add something to the readme

On Friday, August 28, 2015, Chris Dias <notifications@github.com> wrote:

> Closed #1 <https://github.com/chrisdias/ionic-todo-vscode/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisdias/ionic-todo-vscode/issues/1#event-395581731>.
>


-- 

--

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders





This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by chrisdias** [comment]
good idea, thanks!
